name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 2.1.3

      - name: Install dependencies
        run: poetry install

      - name: Check formatting with Black
        run: poetry run black . --check

      - name: Check imports with isort
        run: poetry run isort . --check-only

      - name: Run flake8
        run: poetry run flake8 .

      - name: Run tests
        run: poetry run pytest
